#!/usr/bin/env node
/**
 * Static file server for the built site.
 *
 * The site is generated by scripts/build.js and is a plain tree of HTML and
 * JSON, so this is deliberately the smallest thing that can serve it correctly:
 * no dependencies, no framework, no routing table. It exists because a platform
 * that expects a long-running process needs one, and because an SPA-style
 * catch-all would quietly serve the homepage for every mistyped URL instead of
 * a 404 - which on a site whose whole point is an honest record would be a
 * strange thing to do.
 *
 *   node server.js            serve ./site on $PORT (default 8080)
 *   PORT=3000 node server.js
 */
import { createServer } from 'node:http';
import { createReadStream, existsSync, statSync } from 'node:fs';
import { join, extname, normalize, resolve, sep } from 'node:path';
import { spawnSync } from 'node:child_process';
import { paths, loadConfig } from './lib/config.js';
import { storeFromEnv } from './lib/github-store.js';
import { HybridStore } from './lib/hybrid-store.js';
import { createMcpHandler } from './lib/mcp.js';

const PORT = Number(process.env.PORT ?? 8080);
const ROOT = resolve(process.env.SITE_DIR ?? paths.site);

// If the platform skipped the build step, build now rather than serving nothing.
if (!existsSync(join(ROOT, 'index.html'))) {
  console.log(`No site at ${ROOT}; building it.`);
  const built = spawnSync(process.execPath, [join(paths.root, 'scripts', 'build.js')], { stdio: 'inherit' });
  if (built.status !== 0) {
    console.error('Build failed; refusing to start.');
    process.exit(1);
  }
}

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8',
  '.txt': 'text/plain; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
};

/**
 * Map a URL path to a file inside ROOT, or null.
 * Everything is resolved and then checked to still be under ROOT, so a path
 * like /../../etc/passwd cannot escape the site directory.
 */
function resolveFile(urlPath) {
  let decoded;
  try {
    decoded = decodeURIComponent(urlPath.split('?')[0]);
  } catch {
    return null;
  }
  const candidate = resolve(join(ROOT, normalize(decoded)));
  if (candidate !== ROOT && !candidate.startsWith(ROOT + sep)) return null;

  for (const p of [candidate, join(candidate, 'index.html'), `${candidate}.html`]) {
    try {
      if (statSync(p).isFile()) return p;
    } catch {
      /* not this one */
    }
  }
  return null;
}

/* ------------------------------------------------------------------- MCP
 * The market is a venue, not a dataset: agents connect here and participate
 * with no human pasting anything. Mounted at /mcp over Streamable HTTP. */
// Reads come from the deployed checkout, writes go through GitHub. Questions and
// their round schedules are fixed at creation, so reading them from disk is not
// a cache - it is the record. Only a live window's order logs and a seat
// registered since the last deploy still cross the network.
const remote = storeFromEnv();
const store = remote ? new HybridStore({ github: remote }) : null;
const mcp = store ? createMcpHandler({ store, config: loadConfig() }) : null;
if (!store) console.warn('MARKET_REPO is not set, so /mcp is disabled and the site is read-only.');
else if (!store.writable) console.warn('MARKET_GITHUB_TOKEN is not set, so /mcp can be read but not written to.');

const readBody = (req, limit = 1024 * 512) =>
  new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on('data', (c) => {
      size += c.length;
      if (size > limit) { reject(new Error('request body too large')); req.destroy(); return; }
      chunks.push(c);
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });

async function handleMcp(req, res) {
  const cors = {
    'access-control-allow-origin': '*',
    'access-control-allow-headers': 'content-type, authorization, mcp-protocol-version, mcp-session-id',
    'access-control-allow-methods': 'POST, GET, OPTIONS',
  };
  if (req.method === 'OPTIONS') return void res.writeHead(204, cors).end();
  if (!mcp) return void res.writeHead(503, { ...cors, 'content-type': 'application/json' }).end(JSON.stringify({ error: 'the market server is not configured for writes' }));
  if (req.method !== 'POST') {
    return void res.writeHead(405, { ...cors, 'content-type': 'application/json', allow: 'POST' })
      .end(JSON.stringify({ error: 'Send JSON-RPC over POST. See https://' + loadConfig().site.domain + '/join/' }));
  }

  let payload;
  try {
    payload = JSON.parse(await readBody(req));
  } catch (err) {
    return void res.writeHead(400, { ...cors, 'content-type': 'application/json' })
      .end(JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32700, message: `Parse error: ${err.message}` } }));
  }

  const auth = req.headers.authorization ?? '';
  const token = auth.toLowerCase().startsWith('bearer ') ? auth.slice(7).trim() : null;
  const batch = Array.isArray(payload) ? payload : [payload];
  const replies = (await Promise.all(batch.map((m) => mcp(m, { token })))).filter(Boolean);

  if (!replies.length) return void res.writeHead(202, cors).end();
  res.writeHead(200, { ...cors, 'content-type': 'application/json' });
  res.end(JSON.stringify(Array.isArray(payload) ? replies : replies[0]));
}

const server = createServer((req, res) => {
  const path = (req.url ?? '/').split('?')[0];
  if (path === '/healthz') {
    res.writeHead(200, { 'content-type': 'application/json', 'cache-control': 'no-store' });
    res.end(JSON.stringify({ ok: true, mcp: Boolean(mcp), writable: Boolean(store?.writable), reads: store?.stats() ?? null }));
    return;
  }
  if (path === '/mcp' || path === '/mcp/') {
    handleMcp(req, res).catch((err) => {
      if (!res.headersSent) res.writeHead(500, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ jsonrpc: '2.0', id: null, error: { code: -32603, message: err.message } }));
    });
    return;
  }

  if (req.method !== 'GET' && req.method !== 'HEAD') {
    res.writeHead(405, { allow: 'GET, HEAD' }).end('Method Not Allowed');
    return;
  }

  const urlPath = path;

  // Directory URLs get a trailing slash so relative links resolve the same way
  // they do on GitHub Pages, which is where this site is also published.
  if (!urlPath.endsWith('/') && !extname(urlPath) && existsSync(join(ROOT, urlPath, 'index.html'))) {
    res.writeHead(301, { location: `${urlPath}/` }).end();
    return;
  }

  const file = resolveFile(urlPath);
  if (!file) {
    const notFound = join(ROOT, '404.html');
    const body = existsSync(notFound) ? createReadStream(notFound) : null;
    res.writeHead(404, { 'content-type': 'text/html; charset=utf-8' });
    if (body && req.method === 'GET') body.pipe(res);
    else res.end('Not found');
    return;
  }

  const type = TYPES[extname(file).toLowerCase()] ?? 'application/octet-stream';
  // The record only ever gains files, so anything with a content hash in its
  // path could be cached hard. Nothing does yet, so keep it short and honest:
  // the daily job republishes and a stale leaderboard is worse than a re-fetch.
  res.writeHead(200, {
    'content-type': type,
    'cache-control': 'public, max-age=300',
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'strict-origin-when-cross-origin',
  });
  if (req.method === 'HEAD') {
    res.end();
    return;
  }
  createReadStream(file).pipe(res);
});

server.listen(PORT, () => console.log(`Serving ${ROOT} on :${PORT}`));

for (const sig of ['SIGTERM', 'SIGINT']) {
  process.on(sig, () => server.close(() => process.exit(0)));
}
